---
  - name: register temporary directory
    tempfile:
      state: directory
    register: tmp_directory
    tags:
      - molecule-idempotence-notest

  - name: check vault
    stat:
      path: "{{ vault.bin_directory }}/vault"
    register: vault_stat_result
    tags:
      - vault

  - name: Install vault client
    get_url:
      url: https://releases.hashicorp.com/vault/{{ vault.version }}/vault_{{ vault.version }}_{{ vault.os }}_{{ vault.arch }}.zip
      dest: "{{ tmp_directory.path }}/vault_{{ vault.version }}_{{ vault.os }}_{{ vault.arch }}.zip"
      mode: 0755
    register: vault_download
    when: not vault_stat_result.stat.exists
    tags:
      - vault

  - name: Unzip vault archive
    unarchive:
      src: "{{ vault_download.dest }}"
      dest: "{{ tmp_directory.path }}"
      copy: no
      mode: 0755
    when: not vault_stat_result.stat.exists
    tags:
      - vault

  - name: create bin directory
    include_role:
      name: "check/setup"
    vars:
      path: "{{ vault.bin_directory }}"
      check: "ensure_dir"
    when: not vault_stat_result.stat.exists
    tags:
      - vault

  - name: Move vault binaries
    copy:
      src: "{{ tmp_directory.path }}/{{ bin_item }}"
      dest: "{{ vault.bin_directory }}/{{ bin_item }}"
      mode: 0755
    with_items:
      - vault
    loop_control:
      loop_var: bin_item
    when: not vault_stat_result.stat.exists

  - name: Test vault installation
    shell: |
      printenv
      vault version
    changed_when: false
    tags:
      - molecule-idempotence-notest
