# This is custom git Action created to run molecule test cases during any push on develop branch
name: Molecule Test Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install molecule==3.0.6 yamllint ansible-lint docker==4.2.2 openshift
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      if: |
        contains(github.event.pull_request.title.toLowerCase(), 'shared') ||
        contains(github.event.pull_request.title.toLowerCase(), 'corda') ||
        contains(github.event.pull_request.title.toLowerCase(), 'fabric')
    - name: Test Stage Shared default
      run: |
        cd ./platforms/shared/configuration
        molecule test -s default
      if: contains(github.event.pull_request.title.toLowerCase(), 'shared')
    - name: Test Stage kubernetes-corda
      run: |
        cd ./platforms/shared/configuration
        molecule test -s kubernetes-corda
      if: contains(github.event.pull_request.title.toLowerCase(), 'shared')
    - name: Test Stage kubernetes-fabric
      run: |
        cd ./platforms/shared/configuration
        molecule test -s kubernetes-fabric
      if: contains(github.event.pull_request.title.toLowerCase(), 'shared')
    - name: Test Stage Fabric default
      run: | 
        cd ./platforms/hyperledger-fabric/configuration
        molecule test -s default
      if: contains(github.event.pull_request.title.toLowerCase(), 'fabric')
    - name: Test Stage Fabric default
      run: | 
        cd ./platforms/hyperledger-fabric/configuration
        molecule test -s default
      if: contains(github.event.pull_request.title.toLowerCase(), 'fabric')
    - name: Test Stage Fabric crypto
      run: | 
        cd ./platforms/hyperledger-fabric/configuration
        molecule test -s crypto
      if: contains(github.event.pull_request.title.toLowerCase(), 'fabric')
