# This is custom git Action created to run molecule test cases during any push on develop branch
name: Python application

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install molecule==3.0.6 yamllint ansible-lint docker==4.2.2 openshift
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test Stage one
      run: |
        python --version 
        cd ./platforms/shared/configuration
        molecule test -s kubernetes-corda
